import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ChevronDown, Package, Truck } from 'lucide-react';
import { getBrandOrder, getBrandOrders, updateBrandOrderStatus, updateBrandOrderTracking } from '../../api/brand';
import { useBrand } from '../../contexts/BrandContext';

const labels = { pending_payment: 'Ödeme bekliyor', paid: 'Ödendi', preparing: 'Hazırlanıyor', ready_to_ship: 'Gönderime hazır', shipped: 'Kargoda', delivered: 'Teslim edildi', cancelled: 'İptal', refunded: 'İade' };
const next = { paid: 'preparing', preparing: 'ready_to_ship', shipped: 'delivered' };
const nextLabels = { preparing: 'Hazırlamaya başla', ready_to_ship: 'Gönderime hazırla', delivered: 'Teslim edildi işaretle' };
const money = (v) => `${Number(v || 0).toLocaleString('tr-TR', { minimumFractionDigits: 2 })} ₺`;

export default function BrandOrders() {
  const { brandId } = useBrand(); const queryClient = useQueryClient();
  const [status, setStatus] = useState(''); const [expanded, setExpanded] = useState('');
  const { data, isLoading } = useQuery({ queryKey: ['brandOrders', brandId, status], queryFn: () => getBrandOrders({ brand_id: brandId, status: status || undefined }), enabled: Boolean(brandId) });
  const refresh = () => { queryClient.invalidateQueries({ queryKey: ['brandOrders', brandId] }); queryClient.invalidateQueries({ queryKey: ['brandOrder'] }); queryClient.invalidateQueries({ queryKey: ['brandDashboard', brandId] }); };
  const statusMutation = useMutation({ mutationFn: ({ id, value }) => updateBrandOrderStatus(id, brandId, value), onSuccess: refresh });
  const orders = data?.orders || [];
  return <div><div className="mb-5"><h1 className="font-heading text-2xl font-bold text-walnut">Siparişler</h1><p className="text-sm text-coffee">Kendi ürünlerinize ait gönderileri hazırlayın ve kargolayın.</p></div><select value={status} onChange={(e) => setStatus(e.target.value)} className="mb-4 rounded-lg border border-light-wood bg-white px-3 py-2 text-sm text-walnut"><option value="">Tüm durumlar</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>{isLoading ? <div className="h-32 animate-pulse rounded-xl bg-white" /> : !orders.length ? <div className="rounded-xl bg-white p-10 text-center text-coffee"><Package className="mx-auto mb-2 h-9 w-9 text-light-wood" />Sipariş bulunamadı.</div> : <div className="space-y-3">{orders.map((order) => <div key={order.fulfillment_id} className="overflow-hidden rounded-xl border border-light-wood/60 bg-white"><button onClick={() => setExpanded(expanded === order.fulfillment_id ? '' : order.fulfillment_id)} className="grid w-full gap-2 p-4 text-left text-sm sm:grid-cols-5 sm:items-center"><span className="font-semibold text-walnut">#{order.order_number}</span><span className="text-coffee">{order.customer_name}</span><span className="text-coffee">{labels[order.status]}</span><span className="font-semibold text-walnut">{money(order.total_amount)}</span><ChevronDown className={`h-4 w-4 justify-self-end transition-transform ${expanded === order.fulfillment_id ? 'rotate-180' : ''}`} /></button>{expanded === order.fulfillment_id && <OrderDetail id={order.fulfillment_id} brandId={brandId} onStatus={(value) => statusMutation.mutate({ id: order.fulfillment_id, value })} nextStatus={next[order.status]} />}</div>)}</div>}</div>;
}

function OrderDetail({ id, brandId, onStatus, nextStatus }) {
  const queryClient = useQueryClient(); const [company, setCompany] = useState(''); const [tracking, setTracking] = useState('');
  const { data, isLoading } = useQuery({ queryKey: ['brandOrder', id], queryFn: () => getBrandOrder(id, brandId) });
  const ship = useMutation({ mutationFn: () => updateBrandOrderTracking(id, brandId, { cargo_company: company, tracking_number: tracking }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['brandOrders', brandId] }); queryClient.invalidateQueries({ queryKey: ['brandOrder', id] }); } });
  if (isLoading) return <div className="border-t border-light-wood/50 p-5 text-sm text-coffee">Yükleniyor...</div>;
  return <div className="border-t border-light-wood/50 bg-cream/50 p-4"><div className="grid gap-4 lg:grid-cols-2"><div><h3 className="mb-2 text-sm font-semibold text-walnut">Ürünler</h3>{data.items.map((item) => <div key={item.id} className="mb-2 flex justify-between text-sm"><span className="text-coffee">{item.product_name} × {item.quantity}</span><span className="font-medium text-walnut">{money(Number(item.total_price) - Number(item.allocated_discount))}</span></div>)}</div><div><h3 className="mb-2 text-sm font-semibold text-walnut">Teslimat adresi</h3><p className="text-sm text-coffee">{data.shipping_name} · {data.shipping_phone}</p><p className="mt-1 text-sm text-coffee">{data.shipping_address} {data.shipping_apartment}<br />{data.shipping_district} / {data.shipping_city}</p></div></div><div className="mt-4 grid gap-2 border-t border-light-wood/50 pt-4 text-sm sm:grid-cols-3"><span>Ürün: {money(data.items_subtotal)}</span><span>İndirim: -{money(data.discount_amount)}</span><span className="font-semibold">Kargo: {money(data.shipping_fee)}</span></div><div className="mt-4 flex flex-wrap gap-2">{nextStatus && <button onClick={() => onStatus(nextStatus)} className="rounded-lg bg-walnut px-3 py-2 text-sm font-medium text-white">{nextLabels[nextStatus]}</button>}{data.status === 'ready_to_ship' && <><input value={company} onChange={(e) => setCompany(e.target.value)} placeholder="Kargo firması" className="rounded-lg border border-light-wood px-3 py-2 text-sm" /><input value={tracking} onChange={(e) => setTracking(e.target.value)} placeholder="Takip numarası" className="rounded-lg border border-light-wood px-3 py-2 text-sm" /><button disabled={!company || !tracking || ship.isPending} onClick={() => ship.mutate()} className="flex items-center gap-2 rounded-lg bg-terracotta px-3 py-2 text-sm font-medium text-white disabled:opacity-50"><Truck className="h-4 w-4" />Kargoya ver</button></>}</div></div>;
}
